'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const paths={lock:'M6 10h12v11H6z M8 10V6a4 4 0 0 1 8 0v4 M12 14v3',folder:'M3 6h6l2 2h10v12H3z M3 6V4h6l2 2h10v2',note:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6 M9 15h6 M9 18h5',search:'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',code:'M8 6l-6 6 6 6 M16 6l6 6-6 6 M14 3l-4 18',megaphone:'M3 9v6h5l12 5V4L8 9z M8 15l2 6h3l-2-5',shield:'M12 2l9 4v6c0 5-6 9-9 10-3-1-9-5-9-10V6z M8 12l3 3 5-6',chart:'M3 21h19 M5 18v-5h3v5 M11 18V9h3v9 M17 18V4h3v14 M4 9l7-5 4 1 6-4',person:'M17 7a5 5 0 1 1-10 0 5 5 0 0 1 10 0 M3 22v-3a9 9 0 0 1 18 0v3z',chat:'M3 3h18v14H9l-6 4z M7 8h10 M7 12h7',book:'M5 3h15v19H5a2 2 0 0 1 0-4h15 M5 3a2 2 0 0 0-2 2v15 M8 7h8 M8 11h6',tool:'M14 3a6 6 0 0 0-7 8l-5 7 4 4 7-7a6 6 0 0 0 8-7l-5 4-4-4z',mail:'M2 5h20v15H2z M2 5l10 8L22 5',brain:'M8 3a4 4 0 0 0-4 6 5 5 0 0 0 0 8 4 4 0 0 0 8 3V5a3 3 0 0 0-4-2 M16 3a4 4 0 0 1 4 6 5 5 0 0 1 0 8 4 4 0 0 1-8 3 M5 10l3 2 M19 10l-3 2',sliders:'M2 5h7 M15 5h7 M2 12h12 M20 12h2 M2 19h3 M11 19h11 M9 2v6h6V2z M14 9v6h6V9z M5 16v6h6v-6z'};
function icon(name,cls=''){return `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.note}"/></svg>`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$$('[data-icon]').forEach(e=>e.outerHTML=icon(e.dataset.icon));$('#settings').innerHTML=icon('sliders');$('#lock').innerHTML=icon('lock');
const pending=new Map();let requestID=0;
function call(method,params={}){return new Promise((resolve,reject)=>{if(!window.webkit?.messageHandlers.oracle){reject(Error('O aplicativo macOS é necessário. Este arquivo não é um app web.'));return}const id=String(++requestID);pending.set(id,{resolve,reject});window.webkit.messageHandlers.oracle.postMessage({id,method,params})})}
window.oracleReply=(id,res)=>{const p=pending.get(id);if(!p)return;pending.delete(id);res.error?p.reject(Error(res.error)):p.resolve(res.value)};
let state={entries:[],collections:[],events:[],config:{}},selected=null,view='map',query='',zoom=1,replay=false,cursor=0,timer=null,speed=1,readDocument=null,plan=null,onboarding={answers:{AGENT_NAME:'Oracle'},newVault:false,attach:false,catalogCollections:[]};
const colors=['#dba17c','#91b5ed','#7bc8b4','#d9c276','#b29bd7','#92c399','#d49cae'];
const positions=[[292,132],[564,130],[678,313],[164,310],[248,491],[600,485],[424,574]];
function toast(text){if(!$('#lock-screen').hidden)return;if($('#modal').open){let notice=$('#modal-content .modal-notice');if(!notice){notice=document.createElement('div');notice.className='modal-notice';notice.setAttribute('role','alert');$('#modal-content').append(notice)}notice.textContent=text;return}$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6500)}
function safe(fn){return async(...a)=>{try{return await fn(...a)}catch(e){toast(e.message)}}}
function modal(html){if(!$('#lock-screen').hidden)return;atlasController?.setPaused(true);$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();$('#modal').querySelector('input,button,textarea')?.focus()}
function closeModal(){$('#modal').close();atlasController?.setPaused(document.hidden||view!=='map'||visualPaused)}
function actions(extra=''){return `<div class="actions"><button class="secondary" data-close>Fechar</button>${extra}</div>`}
$('#modal').addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal()});
function skills(id){return visibleEntries().filter(e=>!e.directory&&e.path.startsWith(`SISTEMA/skills/${id}/`)&&e.name==='SKILL.md')}
function title(e){return e.name==='SKILL.md'?e.path.split('/').slice(-2,-1)[0]:e.name.replace(/\.md$/,'')}
async function refresh(){state=await call('snapshot');render();if(state.scanError)toast(state.scanError)}
function render(){if(window.ORACLE_PREVIEW||state.config.fixture){$('.header-sub').textContent='AMBIENTE DE TESTE · DADOS SINTÉTICOS';$('.header-sub').style.color='#b5c9e5'}renderTree();renderAtlas();renderResults();renderProgress();renderInspector();$('#vault-label').textContent=state.config.fixture?'Vault de validação · dados sintéticos':state.config.vault||'Nenhuma pasta conectada';$('#vault-label').title=state.config.vault||'';$('#footer-status').textContent=state.scanError?'FONTE INDISPONÍVEL · '+state.scanError:state.config.vault?`${visibleEntries().filter(e=>!e.directory).length.toLocaleString('pt-BR')} DOCUMENTOS · LEITURA LOCAL`:'LOCAL · FONTES PRESERVADAS';if(window.ORACLE_PREVIEW||state.config.fixture)$('#footer-status').textContent='DEMONSTRAÇÃO · DADOS SINTÉTICOS';$('#codex-status').textContent=state.events.some(e=>e.source==='codex-hook')?'Hooks recebidos · cobertura parcial':'Atividade desconhecida';$('#gbrain-status').textContent=state.config.gbrainWorkspace?'Workspace selecionado · não verificado':'Não verificado';$('#timeline').max=Math.max(0,timelineEvents().length-1);if(!replay)$('#timeline').value=Math.max(0,state.events.length-1);}
function renderTree(){
 const childrenByParent=new Map();for(const e of visibleEntries()){const parent=e.path.split('/').slice(0,-1).join('/');if(!childrenByParent.has(parent))childrenByParent.set(parent,[]);childrenByParent.get(parent).push(e)};const folder=(path,label,open=false)=>{const children=childrenByParent.get(path)||[];return `<details ${open?'open':''}><summary>${icon('folder')}${esc(label||path.split('/').at(-1))}</summary><div>${children.slice(0,30).map(e=>e.directory?folder(e.path,e.name):`<button class="leaf" data-path="${esc(e.path)}">${icon('note')}<span>${esc(e.name.replace('.md',''))}</span></button>`).join('')}${children.length>30?`<button data-prefix="${esc(path)}">Ver todos →</button>`:''}</div></details>`};
 const roots=new Set(visibleEntries().filter(e=>e.directory&&!e.path.includes('/')).map(e=>e.path));
 let html=roots.has('INBOX')?folder('INBOX','Inbox',false):'';
 if(roots.has('PROJETOS'))html+=folder('PROJETOS','Projetos');
 const knowledge=['AREAS','WIKI','FONTES'].filter(x=>roots.has(x));if(knowledge.length)html+=`<details><summary>${icon('folder')}Conhecimento</summary><div>${knowledge.map(p=>folder(p,p==='AREAS'?'Áreas':p==='WIKI'?'Wiki':'Fontes')).join('')}</div></details>`;
 html+=`<div class="tree-section-label">ESPECIALISTAS DIGITAIS</div>`+state.collections.map((c,i)=>`<details ${selected===c.id?'open':''}><summary data-collection="${c.id}">${icon('folder')}<i class="collection-dot" style="background:${colors[i]}"></i>${esc(c.name)}<span class="count">${skills(c.id).length}</span></summary><div>${skills(c.id).filter(e=>!query||title(e).toLowerCase().includes(query)).slice(0,9).map(e=>`<button class="leaf" data-path="${esc(e.path)}">${icon('note')}${esc(title(e).replace(/-/g,' '))}</button>`).join('')}${skills(c.id).length>9?`<button data-prefix="SISTEMA/skills/${c.id}">Ver todas →</button>`:''}${!skills(c.id).length?'<small class="empty-collection">Nenhuma skill nesta fonte</small>':''}</div></details>`).join('');
 if(!state.config.vault)html='<p class="empty">Seu conhecimento, no seu espaço.<button class="primary" data-connect>Conectar vault</button></p>'+html;
 $('#tree').innerHTML=html;$('#tree').querySelectorAll('[data-collection]').forEach(e=>e.onclick=()=>{selected=e.dataset.collection;selectedSkill=null;renderAtlas();renderInspector()});bindPaths($('#tree'));$('#tree').querySelector('[data-connect]')?.addEventListener('click',()=>showSetup(0));$('#tree').querySelectorAll('[data-prefix]').forEach(e=>e.onclick=()=>{query=e.dataset.prefix.toLowerCase();$('#search').value=query;setView('list')});
}
function bindPaths(container){container.querySelectorAll('[data-path]').forEach(e=>e.onclick=safe(()=>{const entry=visibleEntries().find(n=>n.path===e.dataset.path);if(entry?.directory){query=entry.path.toLowerCase();$('#search').value=query;setView('folders')}else return openNote(e.dataset.path)}))}
let atlasController=null, selectedSkill=null, visualPaused=false,replaySession=null,replayProjection=null;
function renderAtlas(){
 if(!atlasController){atlasController=new OracleAtlas($('#atlas'),{onSelect:(id,leaf)=>{selected=id;selectedSkill=leaf;renderInspector()},onOpen:safe(openNote),onLayout:safe(async layout=>{await call('saveLayout',{layout});state.config.layout=layout}),onZoom:value=>{$('#zoom-label').textContent=Math.round(value*100)+'%'}})}
 atlasController.update({collections:state.collections,entries:visibleEntries(),selected,selectedLeaf:selectedSkill,detail:Number($('#density').value),events:replay?timelineEvents().slice(0,cursor+1):state.events,replay,reduced:$('#motion').checked,economy:$('#economy').checked,layout:state.config.layout,hidden:view!=='map'||window.oracleWindowVisible===false,paused:visualPaused||$('#modal').open});
}
function setView(next){view=next;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#atlas').hidden=view!=='map';$('#results').hidden=view==='map';$('.map-tools').hidden=view!=='map';renderResults();atlasController?.setPaused(view!=='map'||document.hidden)}
function renderResults(){if(view==='map')return;let entries=visibleEntries().filter(e=>(view==='folders'||!e.directory)&&(!query||(e.path+' '+title(e)).toLowerCase().includes(query)));$('#results').innerHTML=`<h2>${view==='list'?'Documentos':'Pastas e documentos'} <small>${entries.length} resultados · fonte local</small></h2>`+(entries.length?entries.slice(0,300).map(e=>`<button class="result" data-path="${esc(e.path)}">${icon(e.directory?'folder':'note')}<div><strong>${esc(title(e))}</strong><small>${esc(e.path)}</small></div></button>`).join('')+(entries.length>300?'<p class="empty">Mostrando 300 resultados. Refine a busca.</p>':''):'<p class="empty">Nenhum resultado nesta pasta e filtro.</p>');bindPaths($('#results'))}
const collectionDescriptions={ads:'Estratégia, criação e análise de campanhas.',code:'Procedimentos para projetar, construir e revisar software.',contents:'Seu espaço para procedimentos de conteúdo.','customer-finder':'Pesquisa e descoberta de potenciais clientes.','cyber-security':'Conhecimento e procedimentos de segurança.',marketing:'Pesquisa, posicionamento e crescimento.','personal-branding':'Seu espaço para identidade e marca pessoal.'};
function renderInspector(){if(selectedSkill){renderSkillInspector();return}const c=state.collections.find(c=>c.id===selected);$('#inspector-title').textContent=c?c.name:'Observatório';$('#inspector').innerHTML=c?`<span class="pill">Coleção de procedimentos</span><div class="big-count">${skills(c.id).length}</div><small>skills encontradas na pasta autorizada</small><p class="source">SISTEMA/skills/${c.id}</p><p class="muted">${skills(c.id).length?collectionDescriptions[c.id]:'Nenhuma skill encontrada nesta pasta.'}</p><small class="collection-status">No vault · Codex não verificado</small><button id="view-skills">Explorar coleção →</button>`:'<div class="inspector-orbit">'+icon('brain')+'</div><p class="inspector-welcome">Um universo de possibilidades.</p><p class="muted">Selecione uma constelação. Aproxime para descobrir as skills que fazem parte dela.</p><div class="inspector-tip">'+icon('search')+' Duplo clique para aproximar</div>';$('#view-skills')?.addEventListener('click',()=>{query=`SISTEMA/skills/${c.id}`.toLowerCase();$('#search').value=query;setView('list')})}
function renderProgress(){const events=replay?timelineEvents().slice(0,cursor+1):state.events,folders=events.filter(e=>e.event_type==='setup.folder_verified'),last=events.at(-1);$('#progress-label').textContent=replay?'REPRODUÇÃO DO JOURNAL':'OBSERVAÇÃO LOCAL';$('#status-badge').textContent=window.ORACLE_PREVIEW||state.config.fixture?'Demonstração':replay?'Reprodução':last?'Recibo recebido':state.config.vault?'Fonte local':'Não conectado';$('#progress-title').textContent=state.config.vault?'Seu universo, em perspectiva.':'Seu universo começa aqui';$('#progress-description').textContent=last?last.sanitized_summary:state.config.vault?'Suas notas e especialistas, a partir da pasta selecionada.':'Conecte uma pasta para descobrir seu conhecimento.';$('#progress-count').textContent=folders.length?`${folders.length} pastas verificadas no journal`:`${visibleEntries().filter(e=>!e.directory).length} documentos encontrados`;$('#progress-fill').style.width=folders.length?'100%':'0%';$('#progress-track')?.setAttribute('aria-label','');if(folders.length)$('#progress-title').textContent='Estrutura verificada';if(last?.phase&&Number.isFinite(last.total)){const completed=Math.min(last.completed||0,last.total);$('#progress-title').textContent=last.event_type.endsWith('failed')?'Indexação requer atenção':last.phase==='catalog'?'Organizando especialistas':last.phase==='rollback'?'Reversão verificada':last.phase==='structure'?'Estrutura verificada':'Indexando conhecimento';$('#progress-count').textContent=completed+' de '+last.total+' arquivos verificados';$('#progress-fill').style.width=(last.total?completed/last.total*100:0)+'%'}$('#replay-label').textContent=replay?`${cursor+1}/${timelineEvents().length} · Replay`:'Ao vivo'}
async function openNote(path){readDocument=await call('read',{path});readDocument.relative=path;modal(`<span class="step-label">FONTE CANÔNICA · MARKDOWN</span><h1>${esc(path.split('/').slice(-2).join('/'))}</h1><div class="source">${esc(readDocument.path)}<br>SHA-256 ${readDocument.hash}</div><article class="markdown-reader">${markdown(readDocument.text)}</article>${actions(`<button class="secondary" id="reveal-note">Mostrar no Finder</button>${path.endsWith('SKILL.md')?'<button class="primary" id="edit-note">Criar versão pessoal</button>':''}`)}`);bindMarkdown($('#modal-content'));$('#reveal-note').onclick=safe(()=>call('reveal',{path}));$('#edit-note')?.addEventListener('click',editNote)}
function editNote(){modal(`<h1>Versão pessoal</h1><p>O arquivo do fornecedor será preservado. Revise o diff antes de salvar. O Codex não recarrega esta versão automaticamente.</p><div class="source">${esc(readDocument.relative)} · base ${readDocument.hash.slice(0,12)}</div><textarea class="editor" id="editor" aria-label="Conteúdo SKILL.md" autocorrect="off" autocapitalize="off" spellcheck="false" writingsuggestions="false">${esc(readDocument.text)}</textarea>${actions('<button class="primary" id="diff">Revisar diferenças</button>')}`);$('#diff').onclick=()=>{const value=$('#editor').value;const old=readDocument.text.split('\n'),now=value.split('\n');let lines='';for(let i=0;i<Math.max(old.length,now.length);i++){if(old[i]===now[i])lines+='  '+esc(old[i]??'')+'\n';else{if(old[i]!==undefined)lines+=`<span class="diff-remove">− ${esc(old[i])}</span>\n`;if(now[i]!==undefined)lines+=`<span class="diff-add">+ ${esc(now[i])}</span>\n`}}modal(`<h1>Revisar alteração</h1><p>Uma versão separada será criada com procedência. Se a fonte mudou, sua proposta será preservada como conflito.</p><pre>${lines}</pre>${actions('<button class="primary" id="save-version">Salvar versão pessoal</button>')}`);$('#save-version').onclick=safe(async()=>{const r=await call('saveVersion',{path:readDocument.relative,hash:readDocument.hash,text:value});closeModal();toast(r.status);await refresh()})}}
const fields=[['AGENT_NAME','Como seu agente deve se chamar?',64],['PRINCIPAL_NAME','Como devemos chamar você?',128],['AGENT_PURPOSE','Para que seu segundo cérebro deve servir?',2048],['AGENT_TOP_JOBS','Quais são suas 3 a 5 tarefas recorrentes, em ordem?',2048],['PRINCIPAL_CONTEXT','O que você faz, constrói, valoriza e como trabalha?',4096],['VOICE_REGISTER','Como o agente deve se comunicar? Inclua um exemplo.',1024]];
function captureFields(){$$('[data-answer]').forEach(e=>onboarding.answers[e.dataset.answer]=e.value)}
function showSetup(step){if(step===0){modal(`<span class="step-label">01 / CONECTAR SEU CONHECIMENTO</span><h1>Um lugar para o que você sabe.</h1><p>Oracle apresenta seu conhecimento. O Codex Desktop executa o trabalho de IA; o GBrain oficial organiza a memória. Escolha uma pasta existente ou crie uma pasta vazia no seletor do macOS.</p><div class="source">${esc(state.config.vault||'Nenhuma pasta selecionada')}</div><div class="actions"><button class="secondary" data-close>Agora não</button><button class="primary" id="choose-vault">Escolher pasta…</button></div><label class="check"><input type="checkbox" id="new-vault" ${onboarding.newVault?'checked':''}> Esta é uma pasta nova: criar a estrutura planejada</label><label class="check"><input type="checkbox" id="attach" ${onboarding.attach?'checked':''}> Já tenho GBrain: preservar identidade e conectar instalação existente</label><h2>Especialistas disponíveis</h2><p>Selecione coleções públicas para copiar ao vault. Arquivos existentes com conteúdo diferente são preservados.</p><div class="catalog-choices">${(state.catalog||[]).filter(c=>c.skill_count>0).map(c=>`<label class="check"><input type="checkbox" data-catalog="${c.id}" ${onboarding.catalogCollections.includes(c.id)?'checked':''}> ${esc(state.collections.find(x=>x.id===c.id)?.name||c.id)} <small>${c.skill_count} skills · ${esc(c.license)}</small></label>`).join('')||'<small>Catálogo não disponível neste preview.</small>'}</div><h2>Proteção de acesso</h2><p>Touch ID ou senha do macOS, pela janela segura do sistema. Não criptografa o vault.</p><button class="secondary" id="protect-access">Ativar proteção</button>${actions('<button class="primary" id="next">Continuar</button>')}`);$('#choose-vault').onclick=safe(async()=>{const p=await call('chooseVault');if(p){await refresh();showSetup(0)}});$('#protect-access').onclick=safe(async()=>{await call('protect');toast('Proteção ativada para as próximas aberturas')});$('#next').onclick=safe(async()=>{if(!state.config.vault)throw Error('Escolha uma pasta primeiro');onboarding.newVault=$('#new-vault').checked;onboarding.attach=$('#attach').checked;onboarding.catalogCollections=$$('[data-catalog]:checked').map(e=>e.dataset.catalog);if(onboarding.attach){await call('chooseGBrain');showSetup(4)}else showSetup(1)});return}
if(step<=3){const batch=step===1?fields.slice(0,4):step===2?fields.slice(4,5):fields.slice(5);modal(`<span class="step-label">02 / ENTREVISTA GBRAIN · LOTE ${step} DE 3</span><h1>${['','Seu propósito.','Seu contexto.','Sua voz.'][step]}</h1><p>Respostas literais. Os seis campos oficiais são obrigatórios; você revisará tudo antes de confirmar.</p>${batch.map(([key,label,max])=>`<label class="field">${label}<textarea data-answer="${key}" maxlength="${max}" rows="${max<200?1:3}">${esc(onboarding.answers[key]||'')}</textarea></label>`).join('')}${step===2?`<label class="field">Fuso horário (opcional)<input data-answer="PRINCIPAL_TIMEZONE" value="${esc(onboarding.answers.PRINCIPAL_TIMEZONE||Intl.DateTimeFormat().resolvedOptions().timeZone)}"></label>`:''}${actions('<button class="secondary" id="back">Voltar</button><button class="primary" id="next">Continuar</button>')}`);$('#back').onclick=()=>{captureFields();showSetup(step-1)};$('#next').onclick=safe(()=>{captureFields();if(batch.some(([key])=>!onboarding.answers[key]?.trim()))throw Error('Preencha os campos deste lote');showSetup(step+1)});return}
if(step===4){modal(`<span class="step-label">03 / REVISÃO EXATA</span><h1>Este é o Oracle que você quer?</h1><p>${onboarding.attach?'A identidade existente será preservada. A conexão GBrain ainda precisa de verificação oficial.':'Revise suas respostas. Alterações invalidam a confirmação anterior. O bootstrap oficial GBrain terá sua própria leitura e hash de confirmação.'}</p>${Object.entries(onboarding.answers).filter(([k])=>!onboarding.attach).map(([k,v])=>`<div class="review-field"><strong>${k}</strong><span>${esc(v)}</span></div>`).join('')}<div class="review-field"><strong>DESTINO</strong><span>${esc(state.config.vault)}</span></div><p>${onboarding.newVault?'Criar estrutura padrão: Inbox, Projetos, Áreas, Wiki, Fontes, Diário, Outputs, Arquivo e Sistema.':'Vault existente: nenhuma reorganização ou criação automática da estrutura padrão.'}</p><p>Coleções selecionadas: ${esc(onboarding.catalogCollections.join(', ')||'nenhuma')}. O catálogo local é descoberto pela pasta. A distribuição de novas skills depende de licença e de revisão; nenhuma skill é executada ao aparecer no mapa.</p>${actions('<button class="secondary" id="back">Editar</button><button class="primary" id="confirm-plan">Confirmar e preparar pedido</button>')}`);$('#back').onclick=()=>showSetup(0);$('#confirm-plan').onclick=safe(async()=>{plan=await call('plan',onboarding);await call('confirm',{hash:plan.plan_hash});showSetup(5)});return}
call('briefing').then(brief=>{modal(`<span class="step-label">04 / CONTINUAR NO CODEX</span><h1>O próximo passo acontece no Codex.</h1><p>Seu plano está preparado e confirmado. Copie o pedido e cole em uma tarefa do Codex Desktop. A instalação só aparece em andamento quando os scripts produzirem recibos.</p><pre>${esc(brief)}</pre><p>Hooks novos exigem revisão e confiança no próprio Codex. Oracle não altera essa confiança.</p>${actions('<button class="secondary" id="copy-request">Copiar pedido</button><button class="primary" id="open-codex">Abrir Codex</button>')}`);$('#copy-request').onclick=safe(async()=>{await call('copy',{text:brief});toast('Pedido copiado. Cole na tarefa do Codex.')});$('#open-codex').onclick=safe(()=>call('openCodex'))}).catch(e=>toast(e.message))}
function plugin(){modal(`<span class="step-label">FERRAMENTA / SERVIÇO EXTERNO</span><h1>Gmail</h1><p>Serviço de email do Google. Um conector no Codex pode oferecer leitura, busca e outras ações conforme permissões concedidas lá.</p><span class="pill">No catálogo explicativo</span><span class="pill">Conexão desconhecida</span><p class="source">Origem: mail.google.com · nenhum teste de conexão realizado</p><h2>Você controla o acesso</h2><p>Este cartão não consulta mensagens nem conecta sua conta. Gerencie instalação, conexão e permissões no Codex.</p>${actions('<button class="secondary" id="manage-plugin">Gerenciar no Codex</button><button class="primary" id="open-service">Abrir serviço</button>')}`);$('#manage-plugin').onclick=safe(()=>call('openCodex'));$('#open-service').onclick=safe(()=>call('openService'))}
async function conversations(){const items=await call('conversations');modal(`<span class="step-label">CONVERSAS / IMPORTAÇÃO DELIMITADA</span><h1>Conversas Codex</h1><p>Somente exportações locais Oracle Conversations v1 autorizadas. Este app não consulta os bancos privados do Codex nem todo o histórico ChatGPT/cloud.</p><div id="conversation-list">${items.map((c,i)=>`<button class="result" data-conversation="${i}">${icon('chat')}<div><strong>${esc(c.title)}</strong><small>${esc(c.source)}</small></div></button>`).join('')||'<p class="empty">Nenhuma conversa importada.</p>'}</div>${actions('<button class="primary" id="import-conversations">Importar JSON…</button>')}`);$('#import-conversations').onclick=safe(async()=>{await call('importConversations');await conversations()});$$('[data-conversation]').forEach(e=>e.onclick=()=>{const c=items[Number(e.dataset.conversation)];modal(`<h1>${esc(c.title)}</h1><div class="source">${esc(c.source)} · conteúdo importado</div><pre>${esc(c.messages.map(m=>m.role.toUpperCase()+'\n'+m.text).join('\n\n'))}</pre>${actions()}`)})}
async function instructions(){const items=await call('instructions');modal(`<h1>Instruções dos projetos</h1><p>Arquivos encontrados nas raízes autorizadas. Encontrado não significa aplicado em uma tarefa. Nenhuma instrução é executada pelo Oracle.</p>${items.map((e,i)=>`<button class="result" data-instruction="${i}">${icon('book')}<div><strong>${esc(e.path)}</strong><small>${esc(e.source)}</small></div></button>`).join('')||'<p class="empty">Nenhuma raiz autorizada ou instrução encontrada.</p>'}${actions('<button class="primary" id="add-project">Autorizar projeto…</button>')}`);$('#add-project').onclick=safe(async()=>{await call('chooseProject');await instructions()});$$('[data-instruction]').forEach(e=>e.onclick=safe(async()=>{const doc=await call('readInstruction',items[Number(e.dataset.instruction)]);modal(`<h1>Instrução encontrada</h1><div class="source">${esc(doc.path)}</div><pre>${esc(doc.text)}</pre>${actions()}`)}))}
function activity(){modal(`<h1>Recibos e cobertura</h1><p>Hooks observam apenas caminhos suportados e confiados no Codex. Ferramentas hosted podem não emitir todos os eventos. Stop encerra um turno; silêncio não prova ociosidade, sucesso ou falha.</p><span class="pill">${state.events.filter(e=>e.source==='codex-hook').length} hooks recebidos</span><span class="pill">Sem observação total</span><pre>${esc(state.events.slice(-50).map(e=>`${e.received_at} · ${e.source}\n${e.event_type}: ${e.sanitized_summary}`).join('\n\n')||'Nenhum recibo recebido. A integração não foi comprovada nesta instalação.')}</pre>${actions()}`)}
function settings(){modal(`<h1>Configuração do Oracle</h1><p>Fontes locais autorizadas; nenhuma credencial é lida. Revogar aqui interrompe o acesso pelo Oracle, sem mudar permissões do Codex.</p><div class="source">Vault: ${esc(state.config.vault||'Não selecionado')}<br>GBrain: ${esc(state.config.gbrainWorkspace||'Não selecionado')}</div><div class="actions"><button class="secondary" id="protect-settings">Ativar proteção</button><button class="secondary" id="gbrain-connect">Conectar GBrain existente…</button><button class="secondary" id="gbrain-memory">Consultar memória GBrain</button><button class="secondary" id="bridge-review">Ponte com Codex</button><button class="secondary" id="gbrain-review">Revisar entrevista oficial</button><button class="secondary" id="graphics-diagnostics">Diagnóstico do atlas</button><button class="secondary" id="export-view">Exportar imagem…</button><button class="secondary" id="revoke">Revogar fontes</button><button class="primary" id="restart-setup">Configurar Oracle</button><button class="secondary" data-close>Fechar</button></div>`);$('#restart-setup').onclick=()=>showSetup(0);$('#gbrain-memory').onclick=safe(memory);$('#gbrain-review').onclick=safe(reviewGBrain);$('#bridge-review').onclick=safe(reviewBridge);$('#graphics-diagnostics').onclick=graphicsDiagnostics;$('#export-view').onclick=safe(async()=>{closeModal();const path=await call('exportSnapshot');if(path)toast('Imagem salva: '+path)});$('#gbrain-connect').onclick=safe(async()=>{await call('chooseGBrain');await refresh();settings()});$('#protect-settings').onclick=safe(async()=>{await call('protect');toast('Proteção ativada')});$('#revoke').onclick=safe(async()=>{await call('revoke');selected=null;selectedSkill=null;replay=false;replayProjection=null;replaySession=null;query='';$('#search').value='';await refresh();closeModal()})}
function live(){replay=false;replayProjection=null;replaySession=null;clearInterval(timer);timer=null;$('#play').textContent='▶';render()}
async function ensureReplay(){if(replaySession)return;const data=await call('replayData');if(!data.events?.length)throw Error('Nenhum journal de instalação para reproduzir.');replaySession=data;cursor=0;$('#timeline').max=data.events.length-1}
function projectReplay(){replayProjection=OracleReplay.projectJournal(replaySession.baseline,replaySession.events,cursor);renderTree();renderProgress();renderAtlas();renderResults()}
async function scrub(){try{await ensureReplay();replay=true;cursor=Math.min(Number($('#timeline').value),replaySession.events.length-1);projectReplay()}catch(e){toast(e.message)}}
async function play(){if(timer){clearInterval(timer);timer=null;$('#play').textContent='▶';return}try{await ensureReplay();replay=true;if(cursor>=replaySession.events.length-1)cursor=0;projectReplay();$('#play').textContent='Ⅱ';timer=setInterval(()=>{cursor=Math.min(cursor+1,replaySession.events.length-1);$('#timeline').value=cursor;projectReplay();if(cursor===replaySession.events.length-1){clearInterval(timer);timer=null;$('#play').textContent='▶'}},1000/speed)}catch(e){toast(e.message)}}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#search').oninput=()=>{query=$('#search').value.toLowerCase();if(query)setView('list');renderTree();renderResults()};$('#refresh').onclick=safe(refresh);$('#settings').onclick=settings;$('#setup-button').onclick=()=>state.setup?.confirmed?setupContinuation():showSetup(0);$('#tools').onclick=plugin;$('#gmail').onclick=plugin;$('#activity').onclick=activity;$('#conversations').onclick=safe(conversations);$('#instructions').onclick=safe(instructions);$('#density').oninput=renderAtlas;$('#motion').checked=matchMedia('(prefers-reduced-motion: reduce)').matches;$('#motion').onchange=()=>{document.body.classList.toggle('reduced',$('#motion').checked);renderAtlas()};$('#timeline').oninput=scrub;$('#play').onclick=play;$('#live').onclick=live;$('#speed').onclick=()=>{speed=speed===4?1:speed*2;$('#speed').textContent=speed+'×';if(timer){clearInterval(timer);timer=null;play()}};
function setZoom(factor){atlasController?.zoomAt(factor)}$('#zoom-in').onclick=()=>setZoom(1.2);$('#zoom-out').onclick=()=>setZoom(1/1.2);$('#zoom-reset').onclick=()=>atlasController?.fit();$('#context-back').onclick=()=>atlasController?.back();$('#reset-layout').onclick=()=>{atlasController?.reset();toast('Posições restauradas. Nenhum arquivo foi movido.')};$('#economy').onchange=renderAtlas;
window.oracleLock=()=>{for(const p of pending.values())p.reject(Error('Oracle bloqueado'));pending.clear();replay=false;replayProjection=null;replaySession=null;closeModal();if(atlasController){atlasController.universe?.dispose();atlasController.observer?.disconnect();atlasController=null};$('#lock-screen').hidden=false;$('#app').inert=true;state={entries:[],collections:[],events:[],config:{}};readDocument=null;$('#tree').textContent='';$('#results').textContent='';$('#atlas').textContent='';$('#modal-content').textContent='';clearInterval(timer);timer=null};$('#lock').onclick=safe(async()=>{if(!window.ORACLE_PREVIEW)await call('lock');window.oracleLock()});$('#unlock').onclick=safe(async()=>{await call('unlock');$('#lock-screen').hidden=true;$('#app').inert=false;await refresh()});
// Deterministic ambient dust; it never represents an agent or event.
for(let i=0;i<46;i++){const e=document.createElement('i');e.className='star';e.style.cssText=`left:${(Math.sin(i*12.9898)*43758.5453%1+1)%1*100}%;top:${(Math.sin(i*78.233)*12731.7%1+1)%1*100}%;width:${i%7===0?2:1}px;height:${i%7===0?2:1}px;opacity:${i%5/18+.04}`;$('#galaxy').append(e)}
call('boot').then(async b=>{if(b.locked)window.oracleLock();else await refresh()}).catch(e=>toast(e.message));
setInterval(()=>{if(!$('#lock-screen').hidden||document.hidden)return;call('events').then(events=>{if(events.at(-1)?.event_id!==state.events.at(-1)?.event_id){state.events=events;renderProgress();renderAtlas();if(events.at(-1)?.phase&&!$('#modal').open)safe(refresh)()}}).catch(()=>{})},2500);
setInterval(()=>{if($('#lock-screen').hidden&&!document.hidden&&!$('#modal').open)safe(refresh)()},30000);

async function memory(){
 modal('<h1>Conectando ao GBrain…</h1><p>Consulta à biblioteca oficial, sem inferência. Se outra instância possui o PGLite, o acesso aguardará ou informará a indisponibilidade.</p>'+actions());
 const status=await call('gbrainRead',{operation:'status'});
 $('#gbrain-status').textContent=status.engine+' · conexão verificada';
 modal(`<span class="step-label">MEMÓRIA / GBRAIN OFICIAL ${esc(status.version)}</span><h1>Conhecimento com fonte.</h1><p>Busca textual e links explícitos. Nenhuma consulta a modelos ou serviço de embeddings.</p><label class="field">Fonte autorizada<select id="memory-source">${status.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.id)} · ${esc(s.id)}</option>`).join('')}</select></label><label class="search"><input id="memory-query" placeholder="Buscar na memória" aria-label="Buscar na memória"></label><div id="memory-results"></div>${actions('<button class="primary" id="memory-search">Buscar</button>')}`);
 const source=()=>$('#memory-source').value;
 const renderHits=hits=>{$('#memory-results').innerHTML=hits.map((h,i)=>`<button class="result" data-memory-hit="${i}">${icon('note')}<div><strong>${esc(h.title||h.slug||h.page_slug)}</strong><small>${esc(h.source_id||source())} / ${esc(h.slug||h.page_slug)}</small></div></button>`).join('')||'<p class="empty">Nenhum resultado nesta fonte.</p>';$$('[data-memory-hit]').forEach(e=>e.onclick=safe(()=>memoryPage(hits[Number(e.dataset.memoryHit)].slug||hits[Number(e.dataset.memoryHit)].page_slug,source())))};
 const search=safe(async()=>{const query=$('#memory-query').value;const src=source();if(!src)throw Error('Nenhuma fonte registrada');renderHits(await call('gbrainRead',{operation:query?'search':'list',source:src,query}))});
 $('#memory-search').onclick=search;$('#memory-query').onkeydown=e=>{if(e.key==='Enter')search()};$('#memory-source').onchange=search;if(status.sources.length)await search();
}
async function memoryPage(slug,source){const page=await call('gbrainRead',{operation:'get',source,slug});if(!page)throw Error('Página não encontrada');const links=await call('gbrainRead',{operation:'graph',source,slug});modal(`<h1>${esc(page.title||slug)}</h1><div class="source">${esc(source)} / ${esc(slug)}<br>${esc(page.canonical_path||page.frontmatter?.canonical_path||page.frontmatter?.origin_source_path||'Origem física não informada pela página')}</div><pre>${esc(page.compiled_truth||'')}</pre><h2>Relações explícitas</h2><pre>${esc(JSON.stringify(links,null,2))}</pre>${actions()}`)}
async function reviewGBrain(){const r=await call('gbrainReadback');if(!r.upstream_hash)throw Error('O Codex ainda não preparou a entrevista oficial. Use o pedido de configuração.');modal(`<span class="step-label">REVISÃO OFICIAL GBRAIN</span><h1>Confirme o conteúdo exato.</h1><p>Este texto e hash foram produzidos pelo motor oficial. Confirme somente se refletem suas respostas.</p><pre>${esc(r.readback)}</pre>${actions('<button class="primary" id="confirm-official">Confirmar entrevista oficial</button>')}`);$('#confirm-official').onclick=safe(async()=>{await call('confirmGBrain',{hash:r.upstream_hash});toast('Confirmado. Continue no Codex para renderizar identidade e indexar.');closeModal()})}

function renderSkillInspector(){const path=selectedSkill,name=path.split('/').slice(-2,-1)[0],collection=state.collections.find(c=>c.id===selected);$('#inspector-title').textContent=name.replace(/-/g,' ');$('#inspector').innerHTML=`<span class="pill">Skill · ${esc(collection?.name||'')}</span><p class="muted">Um procedimento da sua coleção de especialistas.</p><div class="source">${esc(path)}</div><button id="inspect-skill" class="primary">Ler procedimento</button><button id="edit-selected-skill" class="secondary">Criar versão pessoal</button><button id="focus-parent">Enquadrar coleção →</button><small>Duplo clique abre a fonte. Arraste ajusta somente o layout.</small>`;$('#inspect-skill').onclick=safe(()=>openNote(path));$('#edit-selected-skill').onclick=safe(async()=>{await openNote(path);editNote()});$('#focus-parent').onclick=()=>atlasController?.focus(selected)}

function graphicsDiagnostics(){modal(`<h1>Diagnóstico do atlas</h1><p>Medidas desta janela, sem estimar tempo de GPU. O movimento ambiental é separado de execução real do Codex.</p><pre>${esc(JSON.stringify(atlasController?.diagnostics()||{renderer:'SVG fallback',reason:atlasController?.renderError},null,2))}</pre>${actions()}`)}

window.oracleVisibility=visible=>{window.oracleWindowVisible=visible;atlasController?.setPaused(!visible||view!=='map'||visualPaused||$('#modal').open);document.body.classList.toggle('window-hidden',!visible)};

$('#ambient-toggle').onclick=()=>{visualPaused=!visualPaused;$('#ambient-toggle').textContent=visualPaused?'Retomar atmosfera':'Pausar atmosfera';atlasController?.setPaused(visualPaused||document.hidden||view!=='map')};

function markdown(text){
 const lines=text.replace(/^---\n[\s\S]*?\n---\n/,'').split('\n');let html='',list=false,code=false,codeLines=[];
 const inline=line=>esc(line).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[\[([^\]]+)\]\]/g,'<button class="wiki-link" data-wiki="$1">$1</button>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<button class="document-link" data-external="$2">$1 ↗</button>');
 for(const line of lines){if(line.startsWith('```')){if(code){html+='<pre><code>'+esc(codeLines.join('\n'))+'</code></pre>';codeLines=[];code=false}else code=true;continue}if(code){codeLines.push(line);continue}const item=/^\s*[-*] (.+)/.exec(line);if(item){if(!list){html+='<ul>';list=true}html+='<li>'+inline(item[1])+'</li>';continue}if(list){html+='</ul>';list=false}const heading=/^(#{1,4}) (.+)/.exec(line);if(heading){html+=`<h${Math.min(heading[1].length+1,4)}>${inline(heading[2])}</h${Math.min(heading[1].length+1,4)}>`}else if(line.startsWith('> '))html+='<blockquote>'+inline(line.slice(2))+'</blockquote>';else if(line.trim())html+='<p>'+inline(line)+'</p>'}
 if(list)html+='</ul>';if(code)html+='<pre><code>'+esc(codeLines.join('\n'))+'</code></pre>';return html||'<p>Documento vazio.</p>';
}
function bindMarkdown(container){container.querySelectorAll('[data-external]').forEach(e=>e.onclick=safe(()=>call('openExternal',{url:e.dataset.external})));container.querySelectorAll('[data-wiki]').forEach(e=>e.onclick=safe(async()=>{const name=e.dataset.wiki.split('|')[0].split('#')[0].toLowerCase();const matches=visibleEntries().filter(n=>!n.directory&&(title(n).toLowerCase()===name||n.path.replace(/\.md$/,'').toLowerCase()===name));if(matches.length===1)await openNote(matches[0].path);else{closeModal();query=name;$('#search').value=name;setView('list');if(!matches.length)toast('Relação citada; documento não encontrado nesta pasta')}}))}

$('#modal').addEventListener('close',()=>atlasController?.setPaused(document.hidden||window.oracleWindowVisible===false||view!=='map'||visualPaused));

function visibleEntries(){return replayProjection||state.entries}
function timelineEvents(){return replay&&replaySession?replaySession.events:state.events}

function setupContinuation(){modal(`<h1>Continuar sua configuração</h1><p>O plano confirmado permanece disponível. A retomada verifica o que já existe e continua pelos recibos, sem criar outro plano.</p><div class="source">Plano ${esc(state.setup.plan_id)}</div>${actions('<button class="secondary" id="new-setup">Nova configuração</button><button class="primary" id="resume-setup">Retomar no Codex</button>')}`);$('#new-setup').onclick=()=>showSetup(0);$('#resume-setup').onclick=()=>showSetup(5)}

async function reviewBridge(){const r=await call('bridgeReceipt');modal(`<h1>Ponte com Codex</h1><p>${r.workspace?'Abra este workspace no Codex e revise os hooks pelo mecanismo oficial.':'A ponte ainda não foi preparada. Continue pelo pedido de configuração.'}</p>${r.workspace?`<div class="source">${esc(r.workspace)}</div><span class="pill">Preparada · confiança não verificada</span><p>A memória usa o perfil isolado do Oracle. A observação cobre tarefas que utilizam este workspace e seus hooks confiados.</p>`:''}<p>${state.events.filter(e=>e.source==='codex-hook').length} recibos de hooks encontrados. Receber um evento não comprova cobertura de todas as ferramentas.</p>${actions('<button class="primary" id="bridge-codex">Abrir Codex</button>')}`);$('#bridge-codex').onclick=safe(()=>call('openCodex'))}
