// Browser-only design preview. Never bundled state or real integration receipts.
if (location.hostname === '127.0.0.1' || location.hostname === 'localhost') {
  window.ORACLE_PREVIEW = true;
  const collections = [['ads','Ads','megaphone'],['code','Code','code'],['contents','Contents','note'],['customer-finder','Customer Finder','search'],['cyber-security','Cybersecurity','shield'],['marketing','Marketing','chart'],['personal-branding','Personal Branding','person']].map(([id,name,icon])=>({id,name,icon}));
  const names={ads:['ads-audit','ads-google','ads-meta','ads-creative'],code:['branch-pr','chained-pr','cognitive-doc-design','comment-writer'],contents:[], 'customer-finder':['first-customer-finder'],'cyber-security':['analyzing-network-traffic','auditing-cloud','detecting-anomalies'],marketing:['ab-testing','ad-creative','ai-seo','analytics','aso'],'personal-branding':[]};
  const files=['INBOX/oracle/Identidade.md','INBOX/oracle-history/conversations/Conversa de exemplo.md','INBOX/oracle-memory/people/Pessoa de exemplo.md','INBOX/oracle-memory/projects/Projeto de exemplo.md','INBOX/oracle-memory/signals/Sinal de exemplo.md','PROJETOS/Meu primeiro projeto.md','WIKI/Conexões e fontes.md','AREAS/Conhecimento.md'];
  for(const [id,skills] of Object.entries(names))for(const skill of skills)files.push(`SISTEMA/skills/${id}/${skill}/SKILL.md`);
  const dirs=new Set();files.forEach(path=>{const parts=path.split('/');parts.pop();for(let i=1;i<=parts.length;i++)dirs.add(parts.slice(0,i).join('/'))});
  const entries=[...dirs].map(path=>({path,name:path.split('/').at(-1),directory:true,source:'Demonstração'})).concat(files.map(path=>({path,name:path.split('/').at(-1),directory:false,source:'Demonstração',size:128})));
  const snapshot={config:{vault:'Vault de demonstração · nenhuma pasta pessoal acessada',layout:JSON.parse(localStorage.getItem('oracle-preview-layout')||'null')},entries,collections,events:[],projects:[],engine:'Demonstração'};
  window.webkit={messageHandlers:{oracle:{postMessage({id,method,params:p}){setTimeout(()=>{let value=null,error=null;switch(method){case 'boot':value={locked:false};break;case 'snapshot':value=snapshot;break;case 'saveLayout':localStorage.setItem('oracle-preview-layout',JSON.stringify(p.layout));snapshot.config.layout=p.layout;value=true;break;case 'events':case 'conversations':case 'instructions':value=[];break;case 'read':value={path:'DEMONSTRAÇÃO/'+p.path,hash:'preview-sem-hash-real',text:p.path.endsWith('SKILL.md')?`---\nname: ${p.path.split('/').at(-2)}\ndescription: Exemplo para testar a navegação visual.\n---\n\n# Preview do Oracle\n\nEste texto é uma fixture de interface, não o conteúdo da skill original.\n\nNo aplicativo macOS, este painel lê a fonte autorizada e permite editar o documento original com recuperação e detecção de conflitos.`:'# Documento de demonstração\n\nO preview permite experimentar a navegação. Acesso real ao vault, autenticação e integrações ficam no aplicativo macOS.'};break;case 'gbrainRead':if(p.operation==='status')value={engine:'Fixture local',version:'teste',sources:[{id:'slow-fixture',name:'Fonte lenta (sintética)'},{id:'fast-fixture',name:'Fonte rápida (sintética)'}]};else if(['list','search'].includes(p.operation))value=[{slug:'fixture',title:'Documento de '+p.source,source_id:p.source}];else if(p.operation==='get')value={title:'Documento de '+p.source,slug:'fixture',source_id:p.source,compiled_truth:'Conteúdo sintético da fonte '+p.source};else value=[];break;case 'copy':navigator.clipboard?.writeText(p.text);value=true;break;case 'unlock':value=true;break;case 'revoke':value=true;break;default:error='Este recurso usa o aplicativo macOS. O navegador está em demonstração visual.'}window.oracleReply(id,error?{error}:{value})},method==='gbrainRead'&&p.operation!=='status'?(p.source==='slow-fixture'?1200:50):40)}}}};
}
