import {WebGLRenderer,Scene,OrthographicCamera,PlaneGeometry,ShaderMaterial,Mesh,BufferGeometry,Float32BufferAttribute,LineSegments,LineBasicMaterial,LineLoop,Points,PointsMaterial,Color,CanvasTexture,MeshBasicMaterial,SRGBColorSpace} from 'three';

const vertex=`varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`;
const noise=`float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);vec2 u=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),u.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),u.x),u.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=a*noise(p);p=mat2(.8,-.6,.6,.8)*p*2.02+vec2(2.5);a*=.5;}return v;}`;
const sunFragment=`varying vec2 vUv;uniform float time;${noise}
void main(){vec2 p=(vUv-.5)*2.;float r=length(p),a=atan(p.y,p.x);float radius=.425;float t=time*.055;
vec2 uv=p/radius;float sphere=sqrt(max(0.,1.-dot(uv,uv)));vec2 warp=vec2(fbm(uv*4.+vec2(t,-t*.4)),fbm(uv*4.-vec2(t*.2,t)));
float granules=fbm(uv*14.+warp*3.+vec2(t,t*.7));float filaments=fbm(uv*7.+warp*5.-vec2(t*.6,t*.3));
float body=1.-smoothstep(radius-.005,radius+.006,r);float limb=pow(max(0.,r/radius),5.);float heat=.46+granules*.50+filaments*.25;
vec3 surface=mix(vec3(.83,.235,.028),vec3(1.,.78,.40),smoothstep(.48,.97,heat));surface+=vec3(.16,.12,.06)*sphere;surface+=vec3(.08,.06,.015)*limb;
float turbulence=fbm(vec2(a*4.,r*14.-t*2.));float rays=pow(.5+.5*sin(a*13.+t*.8+fbm(p*5.+t)*5.),4.);
float corona=exp(-max(0.,r-radius)*14.)*(.18+turbulence*.18+rays*.12)*(1.-body);float outer=exp(-max(0.,r-radius)*5.5)*.045*(1.-body);
float rim=exp(-abs(r-radius)*190.)*.8;vec3 glow=vec3(1.,.53,.14)*(corona+outer)+vec3(1.,.78,.36)*rim;
float alpha=clamp(body+corona+outer+rim,0.,1.);vec3 rgb=body*surface+glow;rgb*=.96+.025*sin(time*.6);gl_FragColor=vec4(rgb/max(alpha,.001),alpha);}`;
const planetFragment=`varying vec2 vUv;uniform vec3 color;uniform float time;uniform float selected;uniform float subdued;uniform float seed;
void main(){vec2 p=(vUv-.5)*2.;float r=length(p);float a=atan(p.y,p.x);float disk=1.-smoothstep(.635,.655,r);float halo=exp(-abs(r-.65)*24.)*.075;float rim=exp(-abs(r-.647)*180.);float light=.045+.045*max(0.,dot(normalize(vec3(p,.7)),normalize(vec3(-.5,.8,.9))));vec3 surface=mix(vec3(.023,.026,.028),color*.28,light*5.);
float band=exp(-abs(p.y*.7+p.x*.24+sin(p.x*3.+seed)*.05)*28.)*.025;surface+=color*band;
float accent=(.36+.45*pow(max(0.,cos(a-2.2)),4.))*rim;float orbit=exp(-abs(r-.81)*120.)*(.5+.5*sin(a*2.+time*.15+seed))*.15*selected;
vec3 c=surface*disk+color*(accent+halo+orbit)+vec3(.45)*rim*.10;float alpha=clamp(disk+halo+rim*.35+orbit,0.,1.);c*=mix(1.,.57,subdued);gl_FragColor=vec4(c,alpha);
#include <colorspace_fragment>
}`;

class OracleUniverse {
 constructor(container){this.host=container;this.scene=new Scene();this.camera=new OrthographicCamera(-500,500,350,-350,.1,100);this.camera.position.z=10;this.nodeMeshes=new Map();this.frames=[];this.costs=[];this.last=0;this.time=0;this.active=true;this.quality='balanced';this.pending=0;this.timeout=0;this.lastGeometry='';this.metrics={renderer:'Three.js r185 · WebGL2',drawCalls:0,triangles:0};
  const canvas=document.createElement('canvas');canvas.className='universe-webgl';canvas.setAttribute('aria-hidden','true');container.prepend(canvas);this.canvas=canvas;
  try{this.renderer=new WebGLRenderer({canvas,alpha:true,antialias:false,powerPreference:'low-power',depth:false,stencil:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=SRGBColorSpace;this.renderer.setClearColor(0x000000,0);this.renderer.sortObjects=false;}catch(e){canvas.remove();this.active=false;throw e}
  this.plane=new PlaneGeometry(1,1);
  this.sunMaterial=new ShaderMaterial({vertexShader:vertex,fragmentShader:sunFragment,uniforms:{time:{value:0}},transparent:true,depthTest:false,depthWrite:false,toneMapped:false});
  this.sun=new Mesh(this.plane,this.sunMaterial);this.sun.scale.set(330,330,1);this.sun.position.z=2;this.sun.renderOrder=3;
  this.setupGalaxy();this.setupOrbits();
  this.edgeGeometry=new BufferGeometry();this.edgeMaterial=new LineBasicMaterial({vertexColors:true,transparent:true,opacity:.55,depthTest:false});this.edges=new LineSegments(this.edgeGeometry,this.edgeMaterial);this.scene.add(this.edges);
  this.leafGeometry=new BufferGeometry();this.leafMaterial=new PointsMaterial({size:3.6,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.8,depthTest:false});this.leafPoints=new Points(this.leafGeometry,this.leafMaterial);this.scene.add(this.leafPoints);
  this.pulseGeometry=new BufferGeometry();this.pulseGeometry.setAttribute('position',new Float32BufferAttribute(new Float32Array(12),3));this.pulseGeometry.setAttribute('color',new Float32BufferAttribute(new Float32Array(12).fill(.7),3));this.pulseMaterial=new PointsMaterial({size:2.8,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.5,depthTest:false});this.pulses=new Points(this.pulseGeometry,this.pulseMaterial);this.pulses.frustumCulled=false;this.scene.add(this.pulses,this.sun);
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.setPaused(true);container.classList.remove('three-enabled');this.metrics.error='WebGL context lost; SVG fallback active'});
  canvas.addEventListener('webglcontextrestored',()=>{container.classList.add('three-enabled');this.setPaused(false)});
  container.classList.add('three-enabled');this.schedule();
 }
 setupGalaxy(){const textureCanvas=document.createElement('canvas');textureCanvas.width=768;textureCanvas.height=384;const ctx=textureCanvas.getContext('2d');
  const haze=ctx.createRadialGradient(380,195,10,380,195,320);haze.addColorStop(0,'rgba(146,130,113,.10)');haze.addColorStop(.25,'rgba(137,135,134,.035)');haze.addColorStop(.65,'rgba(91,93,113,.02)');haze.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=haze;ctx.fillRect(0,0,768,384);
  ctx.save();ctx.translate(384,192);ctx.rotate(-.15);ctx.scale(1,.25);const disk=ctx.createRadialGradient(0,0,0,0,0,320);disk.addColorStop(0,'rgba(204,182,144,.07)');disk.addColorStop(.38,'rgba(181,174,166,.05)');disk.addColorStop(.75,'rgba(125,124,147,.035)');disk.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=disk;ctx.fillRect(-380,-380,760,760);ctx.restore();
  this.nebulaTexture=new CanvasTexture(textureCanvas);this.nebula=new Mesh(new PlaneGeometry(1120,690),new MeshBasicMaterial({map:this.nebulaTexture,transparent:true,opacity:.85,depthTest:false,depthWrite:false}));this.nebula.rotation.z=.38;this.nebula.position.z=-2;this.scene.add(this.nebula);
  const starPositions=[],starColors=[];for(let i=0;i<130;i++){const random=n=>{const a=Math.sin(n*127.1+311.7)*43758.5453;return a-Math.floor(a)};const x=(random(i+2)-.5)*1050,y=(random(i+901)-.5)*690;starPositions.push(x,y,-1);const v=.12+random(i+20)*.22;starColors.push(v*.92,v*.95,v)}const geo=new BufferGeometry();geo.setAttribute('position',new Float32BufferAttribute(starPositions,3));geo.setAttribute('color',new Float32BufferAttribute(starColors,3));this.stars=new Points(geo,new PointsMaterial({size:1.1,sizeAttenuation:false,vertexColors:true,transparent:true,opacity:.8,depthTest:false}));this.scene.add(this.stars);
 }
 setupOrbits(){this.orbits=[];for(const [rx,ry]of [[185,95],[288,156],[395,233]]){const a=[];for(let i=0;i<160;i++){const angle=i/160*Math.PI*2;const x=Math.cos(angle)*rx,y=Math.sin(angle)*ry;a.push(x*.906-y*.423,x*.423+y*.906,-.5)}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(a,3));const line=new LineLoop(g,new LineBasicMaterial({color:0x9ba0a6,transparent:true,opacity:.09,depthTest:false}));this.orbits.push(line);this.scene.add(line)}}
 sync(model){this.model=model;const width=Math.round(model.width),height=Math.round(model.height);if(!width||!height)return;if(this.width!==width||this.height!==height){this.width=width;this.height=height;this.renderer.setSize(width,height,false)}const {x,y,k}=model.camera;this.camera.left=-x/k;this.camera.right=(width-x)/k;this.camera.top=y/k;this.camera.bottom=(y-height)/k;this.camera.updateProjectionMatrix();
  let geometryKey=model.selected+'|'+model.selectedLeaf;for(const n of model.nodes.values()){geometryKey+=`|${n.id}:${n.x.toFixed(2)},${n.y.toFixed(2)}`;let mesh=this.nodeMeshes.get(n.id);if(!mesh){const color=new Color(model.palette[n.index]);const material=new ShaderMaterial({vertexShader:vertex,fragmentShader:planetFragment,uniforms:{color:{value:color},time:{value:0},selected:{value:0},subdued:{value:0},seed:{value:n.index*3.7}},transparent:true,depthTest:false,depthWrite:false,toneMapped:false});mesh=new Mesh(this.plane,material);mesh.scale.set(121,121,1);mesh.position.z=1;this.scene.add(mesh);this.nodeMeshes.set(n.id,mesh)}mesh.position.x=n.x;mesh.position.y=-n.y;mesh.material.uniforms.selected.value=model.selected===n.id?1:0;mesh.material.uniforms.subdued.value=model.selected&&model.selected!==n.id?1:0}
  for(const l of model.leaves.values())geometryKey+=`|${l.id}:${l.x.toFixed(2)},${l.y.toFixed(2)}`;
  if(geometryKey!==this.lastGeometry){this.lastGeometry=geometryKey;this.updateGeometry(model)}
  this.setQuality(model.data?.economy||this.adaptiveEconomy?'economy':'balanced');this.reduced=model.reduced;this.setPaused(model.paused);if(window.oracleWindowVisible!==false&&!document.hidden)this.render(performance.now(),true);
 }
 curve(x1,y1,x2,y2,t,b=.13){const dx=x2-x1,dy=y2-y1,c1x=x1+dx*.34-dy*b,c1y=y1+dy*.34+dx*b,c2x=x1+dx*.72-dy*b*.5,c2y=y1+dy*.72+dx*b*.5,q=1-t;return{x:q*q*q*x1+3*q*q*t*c1x+3*q*t*t*c2x+t*t*t*x2,y:q*q*q*y1+3*q*q*t*c1y+3*q*t*t*c2y+t*t*t*y2}}
 updateGeometry(model){const coords=[],colors=[],leafCoords=[],leafColors=[];const segment=(x1,y1,x2,y2,color,bend=.13)=>{let prev=this.curve(x1,y1,x2,y2,0,bend);for(let i=1;i<=24;i++){const p=this.curve(x1,y1,x2,y2,i/24,bend);coords.push(prev.x,-prev.y,0,p.x,-p.y,0);colors.push(color.r,color.g,color.b,color.r,color.g,color.b);prev=p}};
  for(const n of model.nodes.values()){const color=new Color(model.palette[n.index]);color.multiplyScalar(model.selected?(n.id===model.selected?1.2:.25):.6);segment(0,0,n.x,n.y,color)}
  for(const l of model.leaves.values()){const n=model.nodes.get(l.parent),c=new Color(model.palette[n.index]);c.multiplyScalar(model.selectedLeaf===l.id ? 1.3 : model.selected===l.parent ? .75 : model.selected ? .20 : .40);segment(n.x,n.y,l.x,l.y,c,.06);leafCoords.push(l.x,-l.y,1);leafColors.push(c.r,c.g,c.b)}
  this.edgeGeometry.setAttribute('position',new Float32BufferAttribute(coords,3));this.edgeGeometry.setAttribute('color',new Float32BufferAttribute(colors,3));this.edgeGeometry.computeBoundingSphere();this.leafGeometry.setAttribute('position',new Float32BufferAttribute(leafCoords,3));this.leafGeometry.setAttribute('color',new Float32BufferAttribute(leafColors,3));this.leafGeometry.computeBoundingSphere();
 }
 setQuality(value){if(this.quality===value)return;this.quality=value;this.renderer.setPixelRatio(value==='economy'?1:Math.min(devicePixelRatio,1.5));if(this.width)this.renderer.setSize(this.width,this.height,false)}
 setPaused(value){const was=this.paused;this.paused=!!value;if(this.paused)this.last=0;if(this.paused||this.reduced){cancelAnimationFrame(this.pending);clearTimeout(this.timeout);this.pending=0;this.timeout=0;if(!this.paused&&this.reduced)this.render(performance.now(),true)}else if(was||!this.pending&&!this.timeout)this.schedule()}
 schedule(){if(this.paused||this.reduced||!this.active)return;this.timeout=setTimeout(()=>{this.timeout=0;this.pending=requestAnimationFrame(t=>{this.pending=0;this.render(t);this.schedule()})},this.quality==='economy'?64:24)}
 render(now,forced=false){if(!this.model||this.paused&&!forced)return;const start=performance.now();if(!forced){const delta=this.last?now-this.last:33;this.time+=Math.min(delta,100)/1000;this.frames.push(delta);if(this.frames.length>360)this.frames.shift();this.last=now}
  const t=this.reduced?0:this.time;this.orbits.forEach((orbit,i)=>orbit.material.opacity=.065+Math.sin(t*.13+i)*.018);this.nebula.rotation.z=.38+Math.sin(t*.017)*.018;this.sunMaterial.uniforms.time.value=t;for(const mesh of this.nodeMeshes.values())mesh.material.uniforms.time.value=t;
  const positions=this.pulseGeometry.attributes.position,colors=this.pulseGeometry.attributes.color;const nodes=[...this.model.nodes.values()];for(let i=0;i<4;i++){const n=this.model.selected?this.model.nodes.get(this.model.selected):nodes[(i*2+1)%nodes.length];if(!n)continue;const phase=(t/(12+i*3)+i*.27)%1;let point=this.curve(0,0,n.x,n.y,phase);if(i>1&&this.model.selected){const leaf=[...this.model.leaves.values()].filter(l=>l.parent===n.id)[i-2];if(leaf)point=this.curve(n.x,n.y,leaf.x,leaf.y,phase,.06)}positions.setXYZ(i,point.x,-point.y,1.1);const color=new Color(this.model.palette[n.index]);colors.setXYZ(i,color.r,color.g,color.b)}positions.needsUpdate=true;colors.needsUpdate=true;this.pulses.visible=!this.reduced;this.pulseMaterial.opacity=this.host.classList.contains('real-event')?.95:.36;this.pulseMaterial.size=this.host.classList.contains('real-event')?4.5:2.3;
  this.renderer.render(this.scene,this.camera);this.renderCount=(this.renderCount||0)+1;this.costs.push(performance.now()-start);if(!this.reduced&&this.quality==='balanced'&&!this.model.data?.economy&&this.frames.length>=180&&!this.adaptiveEconomy){const recent=this.frames.slice(-120).sort((a,b)=>a-b);if(recent[Math.floor(recent.length*.95)]>52){this.adaptiveEconomy=true;this.setQuality('economy')}}if(this.costs.length>360)this.costs.shift();this.metrics={...this.metrics,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,buffer:[this.canvas.width,this.canvas.height],quality:this.quality,adaptiveEconomy:!!this.adaptiveEconomy,paused:this.paused,reduced:!!this.reduced};
 }
 diagnostics(){const p=(array,q)=>{if(!array.length)return null;const a=[...array].sort((a,b)=>a-b);return Number(a[Math.floor((a.length-1)*q)].toFixed(2))};return{...this.metrics,paused:!!this.paused,reduced:!!this.reduced,renderCount:this.renderCount||0,samples:this.frames.length,frameIntervalMedianMs:p(this.frames,.5),frameIntervalP95Ms:p(this.frames,.95),cpuSubmitMedianMs:p(this.costs,.5),cpuSubmitP95Ms:p(this.costs,.95),note:'CPU submission time is not GPU frame time; idle render cadence is deliberately capped.'}}
 dispose(){this.setPaused(true);this.scene.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose()});this.nebulaTexture.dispose();this.renderer.dispose();this.canvas.remove()}
}
window.OracleUniverse=OracleUniverse;
