import {projectJournal} from '../packages/contracts/replay.js';
import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const baseline=[{path:'existing.md',directory:false,name:'existing.md'}];
const events=[{subject_refs:[{path:'SISTEMA/skills/code/fixture/SKILL.md',directory:false}]},{removed_refs:[{path:'SISTEMA/skills/code/fixture',directory:true}]},{subject_refs:[{path:'../escape.md',directory:false}]}];
const before=JSON.stringify({baseline,events});
assert.equal(projectJournal(baseline,events,-1).length,1);
assert(projectJournal(baseline,events,0).some(x=>x.path.endsWith('SKILL.md')));
assert(!projectJournal(baseline,events,2).some(x=>x.path.includes('fixture')||x.path.includes('escape')));
assert.equal(JSON.stringify({baseline,events}),before);
assert.deepEqual(projectJournal(baseline,events,2),projectJournal(baseline,events,2));
writeFileSync('docs/evidence/replay-contract.json',JSON.stringify({baseline:true,creation:true,rollback:true,path_boundary:true,deterministic:true,inputs_unchanged:true},null,2));
console.log('PASS replay baseline, creation, rollback, path boundary and deterministic projection');
